# -*- coding: utf-8 -*-
"""language_modal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMpwcHqU1rASxV204H0LTbObdablU9p_
"""

from langchain.chat_models import ChatOpenAI
from langchain.agents import create_json_agent
from langchain.agents.agent_toolkits import JsonToolkit
from langchain.tools.json.tool import  JsonSpec
import json

file="myData.json"
with open(file,"r") as f1:
    data=json.load(f1)
    f1.close()

spec=JsonSpec(dict_=data,max_value_length=4000)
toolkit=JsonToolkit(spec=spec)

agent=create_json_agent(llm=ChatOpenAI(temperature=0,openai_api_key="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",model="gpt-3.5-turbo"),toolkit=toolkit,max_iterations=1000,verbose=True)
print(agent.run("what is the address of The Restaurant at The Trans Luxury Hotel"))
# print(agent.run("What is the highest rating?"))
# print(agent.run("what is the rating of Bijan?"))

# Commented out IPython magic to ensure Python compatibility.
# %env OPENAI_API_KEY=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